name: Create and publish package
on:
  push:
    branches: ['release']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create package
        uses: zip -r -q DarkwindUI.mpackage src