name: Create and publish package
on:
  push:
    branches: ['release']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create package
        run: zip -r -q DarkwindUI.mpackage src

      - name: Publish package
        uses: actions/upload-artifact@v3
        with:
          name: DarkwindUI.mpackage
          path: DarkwindUI.mpackage